Import the necessery modules

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('strongstravacombo.csv')
df.tail()

,Unnamed: 0,Date,Distance,Duration,Exercise Name,Notes,RPE,Reps,Seconds,Set Order,Source,Speed,Weight,Workout Name,Workout Notes
2705,2564,2022-03-16 12:29:28,0.0,1h 16m,Lat Pulldown,NaN,NaN,5.0,0,4.0,strong,NaN,85.0,Midday Workout,NaN
2706,2565,2022-03-16 12:29:28,0.0,1h 16m,Lat Pulldown,NaN,NaN,5.0,0,5.0,strong,NaN,85.0,Midday Workout,NaN
2707,2566,2022-03-16 12:29:28,0.0,1h 16m,Plank,NaN,NaN,0.0,195,1.0,strong,0.0,0.0,Midday Workout,NaN
2708,2559,2022-03-16 12:29:28,0.0,1h 16m,Squat (Barbell),NaN,NaN,3.0,0,4.0,strong,NaN,45.0,Midday Workout,NaN
2709,2558,2022-03-16 12:29:28,0.0,1h 16m,Squat (Barbell),NaN,NaN,5.0,0,3.0,strong,NaN,40.0,Midday Workout,NaN

 Find all the times I cycled

In [4]:
calc = df[df['Exercise Name'] == 'Cycling']

Calculate the total amount of kms cycled and calculate an average per session

In [5]:
calc

,Unnamed: 0,Date,Distance,Duration,Exercise Name,Notes,RPE,Reps,Seconds,Set Order,Source,Speed,Weight,Workout Name,Workout Notes
376,377,2016-05-21 10:05:32,3100.0,14h 52m,Cycling,NaN,NaN,0.0,600,1.0,strong,18.600000,0.0,Free Workout,NaN
537,537,2016-08-21 17:53:47,23000.0,52s,Cycling,NaN,NaN,0.0,7200,1.0,strong,11.500000,0.0,Afternoon Workout,NaN
617,617,2016-12-09 21:07:41,9060.0,20m,Cycling,147 cal,NaN,0.0,1860,1.0,strong,17.535484,0.0,Evening Workout,NaN
931,142,2017-07-28 20:10:44,33529.3,NaN,Cycling,NaN,NaN,NaN,9896,NaN,strava,12.197401,NaN,NaN,NaN
986,141,2017-09-17 15:09:29,8421.9,NaN,Cycling,NaN,NaN,NaN,1743,NaN,strava,17.394630,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2674,0,2022-03-06 13:16:10,53813.6,NaN,Cycling,NaN,NaN,NaN,8302,NaN,strava,23.335216,NaN,NaN,NaN
2675,2532,2022-03-07 12:20:12,11640.0,48m,Cycling,241 cal,NaN,0.0,1200,1.0,strong,34.920000,0.0,Midday Workout,NaN
2685,2541,2022-03-09 12:26:22,5770.0,1h 3m,Cycling,127 cal,NaN,0.0,600,1.0,strong,34.620000,0.0,Midday Workout,NaN
2697,2554,2022-03-14 13:01:36,11980.0,5m,Cycling,251 cal,NaN,0.0,1200,1.0,strong,35.940000,0.0,Midday Workout,NaN
2698,2555,2022-03-16 12:29:28,3080.0,1h 16m,Cycling,73 cal,NaN,0.0,300,1.0,strong,36.960000,0.0,Midday Workout,NaN

In [15]:
totalKM = (calc['Distance'].sum())/1000
totalKM

8018.9758999999995

In [16]:
amount_of_sessions = calc.shape[0]
amount_of_sessions

251

In [17]:
averagedist = totalKM/amount_of_sessions
averagedist

31.948111155378484

In [18]:
meandistance = calc['Distance'].mean()
meandistance

31948.11115537847

In [19]:
mediandistance = calc['Distance'].median()
mediandistance

18180.0